#general config paramaters
creation_date: 2011-09-07


# server parameters
host: gerrit.wikimedia.org
port: 29418

# Gerrit repository settings
# ignore gerrit projects that contain either of the following strings
ignore_repos:
    - test
    - private

parents:
    - name: mediawiki
      description: 'Aggregate statistics for the entire mediawiki code base (core, extensions, tools and packages.)'
    - name: mediawiki/all_extensions
      description: Aggregate statistics for all extensions.
    - name: mediawiki/wmf_extensions
      description: Aggregate statistics for extensions run by WMF.
    - name: mediawiki/core_wmf_extensions
      description: Aggregate statistics for extensions run by WMF and Mediawiki Core.
    - name: operations
      description: Aggregate statistics for all operations repositories.
    - name: analytics
      description: Aggregate statistics for all analytics repositories.
    - name: integration
      description: Aggregate statistics for all integration repositories.
    - name: labs
      description: Aggregate statistics for all labs repositories.
    - name: translatewiki
      description: Aggregate statistics for all translatewiki repositories.
    - name: wikimedia
      description: Aggregate statistics for all wikimedia repositories.
